In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from collections import Counter
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
!from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
import joblib

from: can't read /var/mail/catboost


In [ ]:
df = pd.read_csv("/content/preprocessed_1.csv",on_bad_lines='skip')


In [ ]:
df = df.reset_index()
df.fillna(0, inplace=True)
Y = df["Summary"]
X = df.drop(["Summary"], axis=1)


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# fit the scaler object on the data
scaler.fit(X)

# transform the data to standard scale
X_std = scaler.transform(X)
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size =0.2, stratify = Y, random_state = 0)

In [ ]:
sm=SMOTE(random_state=0)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_res)))

The number of classes before fit Counter({1.0: 9514, 2.0: 7508, 3.0: 4648, 4.0: 3786, 5.0: 1946})
The number of classes after fit Counter({1.0: 9514, 2.0: 9514, 4.0: 9514, 3.0: 9514, 5.0: 9514})


In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
# Create a pipeline for standardization and KNN
pipe = Pipeline([('scaler', StandardScaler()), ('knn', KNeighborsClassifier())])

# Set hyperparameters for KNN
params = {'knn__n_neighbors': [3, 5, 7], 'knn__weights': ['uniform', 'distance']}

# Use grid search to find the best hyperparameters
grid = GridSearchCV(pipe, params, cv=5)
grid.fit(X_train, y_train)

# Get the test accuracy of the model
test_accuracy = grid.score(X_test, y_test)
print("Test accuracy: {:.2f}".format(test_accuracy))


Test accuracy: 0.55


In [ ]:
import tensorflow as tf
import numpy as np

# define the hyperparameters
learning_rate = 0.01
epochs = 100

# define the linear regression model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])

# compile the model with the optimizer and loss function
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate),
              loss='mean_squared_error')

# train the model for the specified number of epochs
model.fit(X_train, y_train, epochs=100)

# make predictions on new data
y_predT = model.predict(X_test)
print(accuracy_score(y_test,y_predT))
# print the predictions
print(y_pred)


Epoch 1/100


ValueError: ignored

In [ ]:
gnb = GaussianNB()
gnb.fit(X_train_res, y_train_res)
y_pred3 = gnb.predict(X_test)
print(confusion_matrix(y_test,y_pred3))
print(accuracy_score(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

[[1841  226  201   87   23]
 [1167  353  263   74   20]
 [ 395  218  399   58   92]
 [ 586   63  165  105   28]
 [   0    0   12    9  466]]
0.4618303897241279
              precision    recall  f1-score   support

         1.0       0.46      0.77      0.58      2378
         2.0       0.41      0.19      0.26      1877
         3.0       0.38      0.34      0.36      1162
         4.0       0.32      0.11      0.16       947
         5.0       0.74      0.96      0.84       487

    accuracy                           0.46      6851
   macro avg       0.46      0.47      0.44      6851
weighted avg       0.43      0.46      0.41      6851



In [ ]:
sns.pairplot(df,hue="Summary")

In [ ]:
rf=RandomForestClassifier()
rf.fit(X_train_res,y_train_res)
y_pred1 = rf.predict(X_test)
print(confusion_matrix(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

[[1541  442  106  288    1]
 [ 515 1000  254  108    0]
 [  70  204  857   31    0]
 [ 253   74   42  576    2]
 [   0    0    0    1  486]]
0.6509998540359072
              precision    recall  f1-score   support

         1.0       0.65      0.65      0.65      2378
         2.0       0.58      0.53      0.56      1877
         3.0       0.68      0.74      0.71      1162
         4.0       0.57      0.61      0.59       947
         5.0       0.99      1.00      1.00       487

    accuracy                           0.65      6851
   macro avg       0.70      0.70      0.70      6851
weighted avg       0.65      0.65      0.65      6851



In [ ]:
xgb = XGBClassifier()
import numpy as np

# Convert the target variable to integer

y = y_train_res.astype(int)
y_mapped = y - 1
xgb.fit(X_train_res, y_mapped)
y_pred6 = xgb.predict(X_test)
print(confusion_matrix(y_test.astype(int),y_pred6))
print(accuracy_score(y_test.astype(int),y_pred6))
print(classification_report(y_test.astype(int),y_pred6))

[[   0    0    0    0    0    0]
 [2249  386   97  260    0    0]
 [ 462 1502  267  122    0    0]
 [  88  171 1181   23    0    0]
 [ 189   50   31  898    0    0]
 [   0    0    0    0  587    0]]
0.07894429522363658
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.18      0.13      0.15      2992
           2       0.17      0.11      0.14      2353
           3       0.02      0.02      0.02      1463
           4       0.00      0.00      0.00      1168
           5       0.00      0.00      0.00       587

    accuracy                           0.08      8563
   macro avg       0.06      0.04      0.05      8563
weighted avg       0.11      0.08      0.09      8563



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

In [ ]:
svc = SVC()
svc.fit(X_train_res, y_train_res)
y_pred5 = svc.predict(X_test)
print(confusion_matrix(y_test,y_pred5))
print(accuracy_score(y_test,y_pred5))
print(classification_report(y_test,y_pred5))

[[486 843  13 813 223]
 [310 745  30 578 214]
 [239 375  29 307 212]
 [155 292  11 371 118]
 [ 92 179   8 107 101]]
0.2528098087870384
              precision    recall  f1-score   support

         1.0       0.38      0.20      0.27      2378
         2.0       0.31      0.40      0.35      1877
         3.0       0.32      0.02      0.05      1162
         4.0       0.17      0.39      0.24       947
         5.0       0.12      0.21      0.15       487

    accuracy                           0.25      6851
   macro avg       0.26      0.25      0.21      6851
weighted avg       0.30      0.25      0.24      6851



In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

# calculate the test accuracy of the model
test_accuracy = lr.score(X_test, y_test)
print("Test accuracy: {:.2f}".format(test_accuracy))

Test accuracy: 0.26


In [ ]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression

# Assume X and y are your data and target variables
kf = KFold(n_splits=5, shuffle=True)
lr = LinearRegression()

# Loop over the folds and fit the model
for train_idx, test_idx in kf.split(X):
    X_train, y_train = X.iloc[train_idx], Y.iloc[train_idx]
    X_test, y_test = X.iloc[test_idx], Y.iloc[test_idx]
    lr.fit(X_train, y_train)
    score = lr.score(X_test, y_test)
    print("Accuracy:", score)


Accuracy: 0.24658937149295546
Accuracy: 0.25573040095256794
Accuracy: 0.2722780992752484
Accuracy: 0.2788099130575148
Accuracy: 0.2725546771131766


In [ ]:
from sklearn.model_selection import KFold
from sklearn.neural_network import MLPClassifier

# Define the model with hyperparameters
model = MLPClassifier(learning_rate_init=0.001, max_iter=3000)

# Define the number of folds for k-fold cross-validation
k = 4
kf = KFold(n_splits=k, shuffle=True)

# Loop over the folds
scores = []
for train_idx, test_idx in kf.split(X):
    # Split the data into train and test sets
    X_train, y_train = X.iloc[train_idx], Y.iloc[train_idx]
    X_test, y_test = X.iloc[test_idx], Y.iloc[test_idx]
    
    # Fit the model on the training data
    model.fit(X_train, y_train)
    
    # Evaluate the model on the test data
    score = model.score(X_test, y_test)
    scores.append(score)

# Compute the mean and standard deviation of the scores
mean_score = np.mean(scores)
std_score = np.std(scores)

print(f"Mean accuracy: {mean_score:.3f} +/- {std_score:.3f}")


Mean accuracy: 0.341 +/- 0.087


In [ ]:
logreg = LogisticRegression()
logreg.fit(X_train_res, y_train_res)
y_pred2 = logreg.predict(X_test)
print(confusion_matrix(y_test,y_pred2))
print(accuracy_score(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

[[1206  429  225  349  140]
 [ 825  330  284  306  166]
 [ 297  207  262  131  260]
 [ 408  141   71  177  158]
 [  23   24   21   11  399]]
0.3465693430656934
              precision    recall  f1-score   support

         1.0       0.44      0.51      0.47      2349
         2.0       0.29      0.17      0.22      1911
         3.0       0.30      0.23      0.26      1157
         4.0       0.18      0.19      0.18       955
         5.0       0.36      0.83      0.50       478

    accuracy                           0.35      6850
   macro avg       0.31      0.39      0.33      6850
weighted avg       0.33      0.35      0.33      6850



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
!pip install catboost
from catboost import CatBoostClassifier
cat = CatBoostClassifier(iterations=3000, eval_metric = "AUC")
cat.fit(X_train_res, y_train_res)
y_pred = cat.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Learning rate set to 0.03808
0:	total: 31.9ms	remaining: 1m 35s
1:	total: 60.2ms	remaining: 1m 30s
2:	total: 86.4ms	remaining: 1m 26s
3:	total: 108ms	remaining: 1m 20s
4:	total: 139ms	remaining: 1m 23s
5:	total: 161ms	remaining: 1m 20s
6:	total: 184ms	remaining: 1m 18s
7:	total: 211ms	remaining: 1m 18s
8:	total: 232ms	remaining: 1m 17s
9:	total: 255ms	remaining: 1m 16s
10:	total: 278ms	remaining: 1m 15s
11:	total: 300ms	remaining: 1m 14s
12:	total: 323ms	remaining: 1m 14s
13:	total: 346ms	remaining: 1m 13s
14:	total: 369ms	remaining: 1m 13s
15:	total: 390ms	remaining: 1m 12s
16:	total: 417ms	remaining: 1m 13s
17:	total: 439ms	remaining: 1m 12s
18:	total: 461ms	remaining: 1m 12s
19:	total: 484ms	remaining: 1m 12s
20:	total: 508ms	remaining: 1m 12s
21:	total: 536ms	remaining: 1m 12s
22:	total: 565ms	remaining: 1m 13s
23:	total: 586ms	remaining: 1m 12s
24:	total: 608ms	remaining: 1m 12s
25:	

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb=GaussianNB()

#training the model
nb.fit(X_train,y_train)

#testing the model
y_pred=nb.predict(X_test)
metrics.accuracy_score(y_test,y_pred)

0.4475912408759124

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_leaf_nodes=50, random_state=0)
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)
metrics.accuracy_score(y_test,y_pred)

0.5204379562043796

In [ ]:
for i in range (1,20):
  knn = KNeighborsClassifier(n_neighbors=i)
  knn.fit(X_train_res, y_train_res)
  y_pred4 = knn.predict(X_test)
  #print(confusion_matrix(y_test,y_pred4))
  print(accuracy_score(y_test,y_pred4))
  #print(classification_report(y_test,y_pred4))

0.9208759124087591
0.843065693430657
0.7856934306569343
0.7640875912408759
0.7316788321167883
0.7218978102189781
0.7013138686131387
0.6908029197080292
0.675036496350365
0.6684671532846715
0.6537226277372262
0.6454014598540146
0.6345985401459854
0.6272992700729927
0.6157664233576642
0.6102189781021898
0.6032116788321168
0.6014598540145986
0.5943065693430657
